import { copyFileSync } from "node:fs";
import { builtinModules } from "node:module";
import { resolve } from "node:path";
import { defineConfig } from "vite";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE/ROLLUP
if you want to view the source, please visit the github repository of this plugin
*/`;

const externalModules = [
	"obsidian",
	"electron",
	"@codemirror/autocomplete",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
	...builtinModules,
];

export default defineConfig(({ mode }) => {
	const isProduction = mode === "production";
	const outputFile = resolve(__dirname, "dist/main.js");
	const rootMainFile = resolve(__dirname, "main.js");

	return {
		build: {
			target: "es2020",
			emptyOutDir: true,
			outDir: "dist",
			sourcemap: isProduction ? false : "inline",
			minify: isProduction,
			lib: {
				entry: resolve(__dirname, "src/main.ts"),
				formats: ["cjs"],
			},
			rollupOptions: {
				external: externalModules,
				output: {
					entryFileNames: "main.js",
					banner,
				},
			},
		},
		plugins: [
			{
				name: "sync-main-output",
				writeBundle() {
					copyFileSync(outputFile, rootMainFile);
				},
			},
		],
	};
});
